version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "nspool"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    assignees:
      - "nspool"
