version: '2'

services:
  dev:
    image: nrmn-build
    build:
      context: .
      dockerfile: ./Dockerfile.build
      args:
        BUILDER_UID: 1000
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - './:/app'
      - '${HOME}/.m2:/home/builder/.m2'

