BEGIN;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Gobiodon sp. [ceramis cf]' WHERE observable_item_id = 6692;
DELETE FROM nrmn.observable_item_ref WHERE observable_item_id = 320;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Eviota sp. [cf teresae]' WHERE observable_item_id = 8024;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Bovichtidae spp.' WHERE observable_item_id = 1728;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Blenniidae sp. (Jurien)' WHERE observable_item_id = 1580;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Zygometridae sp. [Catoptometra rubroflava cf]' WHERE observable_item_id = 6933;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Muricidae sp. [black spots]' WHERE observable_item_id = 6924;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Gastropoda sp. [purple aperture Red Sea]' WHERE observable_item_id = 7016;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Diogenidae sp. [white claw black blotch]' WHERE observable_item_id = 7021;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pseudanthias sp. [ cf cooperi]' WHERE observable_item_id = 5284;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Cirrhilabrus sp. [cf scottorum]' WHERE observable_item_id = 5285;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pomacentrus ap. [cf australis]' WHERE observable_item_id = 5288;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Gobiodon sp. [cf histrio]' WHERE observable_item_id = 5321;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Scorpaenopsis sp. [cf ramaraoi]' WHERE observable_item_id = 5327;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Oplopomus sp. [atherinoides cf]' WHERE observable_item_id = 5340;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Nectamia sp. [cf luxuria]' WHERE observable_item_id = 5342;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pseudanthias sp. [cf tuka]' WHERE observable_item_id = 5344;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Cirripectes sp. [cf variolosus]' WHERE observable_item_id = 5345;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pseudochromis sp. [cf andamanensis]' WHERE observable_item_id = 5347;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Eviota sp. [cf punctulata]' WHERE observable_item_id = 5348;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Ecsenius sp. [cf frontalis]' WHERE observable_item_id = 5443;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pilumnus monilifera' WHERE observable_item_id = 1592;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Labracinus sp. [ cf cyclophthalmus]' WHERE observable_item_id = 5604;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Eviota ?nigriventris' WHERE observable_item_id = 5605;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Gladiogobius sp. [cf brevispinis]' WHERE observable_item_id = 5606;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pseudochromis sp. [cyanotaenia cf]' WHERE observable_item_id = 5617;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Scorpaenopsis sp. [cf cirrosa]' WHERE observable_item_id = 5669;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Notocypraea comptonii' WHERE observable_item_id = 1711;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Thelenota rubralineata' WHERE observable_item_id = 5895;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Astropyga spp.' WHERE observable_item_id = 6381;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Nesogobius sp. [5]' WHERE observable_item_id = 6740;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Opisthobranchia spp.' WHERE observable_item_id = 6767;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Nesogobius sp. [6]' WHERE observable_item_id = 6786;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Nesogobius sp. [8]' WHERE observable_item_id = 6787;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Nesogobius sp. [2]' WHERE observable_item_id = 6788;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Blenniidae sp. (mottled brown)' WHERE observable_item_id = 6808;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Holothuriidae sp. (Bohadschia graeffei?)' WHERE observable_item_id = 6868;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Blenniidae sp. (Yellow head black body)' WHERE observable_item_id = 6937;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Platyhelminthes sp. [Elysia]' WHERE observable_item_id = 7051;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Platyhelminthes sp. [yellow spots white margin]' WHERE observable_item_id = 7055;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Blenniidae sp. [cheek patch]' WHERE observable_item_id = 7096;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Mitridae sp. (black)' WHERE observable_item_id = 6932;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Flabellina sp. [cf bicolor]' WHERE observable_item_id = 5624;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Colobometra sp. [perspinosa cf]' WHERE observable_item_id = 5320;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Elysia sp. [cf ornata]' WHERE observable_item_id = 5614;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Pseudoceros rubronanus' WHERE observable_item_id = 6468;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Amblypneustes sp. [3]' WHERE observable_item_id = 6764;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Austrodoris kerguelenensis' WHERE observable_item_id = 6031;
UPDATE nrmn.observable_item_ref SET observable_item_name = 'Bornella stellifera' WHERE observable_item_id = 1879;
END;