#This script cleans the database output generated by:
#SELECT observable_item_name  FROM observable_item_ref  WHERE obs_item_type_id IN (1, 2, 3);
#It removes:
#Any occurrences of ssp. or sp.
#Any text enclosed in parentheses () or square brackets []
#The result is a cleaned version of the observable_item_name.



import csv
import re

INPUT_CSV = "Obs_itemlist_for_WoRMS_Update.csv"
OUTPUT_CSV = "Obs_item_list_clean.csv"

def clean_name(name):
    if not name:
        return ""

    name = re.sub(r"\(.*?\)", "", name)
    name = re.sub(r"\[.*?\]", "", name)
    name = re.sub(r"\bsp{1,2}\.\s*", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\s+", " ", name).strip()

    return name


def main():
    with open(INPUT_CSV, newline="", encoding="utf-8-sig") as infile, \
         open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as outfile:

        reader = csv.DictReader(infile, delimiter=',', quotechar='"')

        # Normalize headers
        reader.fieldnames = [f.strip() for f in reader.fieldnames]

        writer = csv.writer(outfile)
        writer.writerow(["observable_item_id", "observable_item_name"])

        for row in reader:
            obs_item_id = row.get("observable_item_id", "")
            original_name = row.get("observable_item_name", "")

            cleaned = clean_name(original_name)

            writer.writerow([obs_item_id, cleaned])


if __name__ == "__main__":
    main()