BEGIN;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402381;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402382;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402383;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402384;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402385;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402386;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402387;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402388;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402389;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402390;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402391;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402392;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402393;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402394;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402395;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402396;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402397;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402398;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402399;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402400;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402401;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402402;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402403;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402404;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402405;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402406;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402407;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402408;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402409;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402410;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402411;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402412;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402413;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402414;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402415;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402416;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402417;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402418;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402419;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402420;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402421;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402422;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402423;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402424;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402425;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402426;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402427;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402428;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402429;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402430;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402431;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402432;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402433;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402434;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402435;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402436;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402437;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402438;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402439;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402440;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402441;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402442;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402443;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402444;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402445;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402446;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402447;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402448;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402449;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402450;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402451;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402452;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402453;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402454;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402455;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402456;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402457;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402458;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402459;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402460;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402461;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402462;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402463;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402464;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402465;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402466;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402467;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402468;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402469;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402470;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402471;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402472;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402473;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402474;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402475;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402476;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402477;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402478;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402479;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402480;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402481;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402482;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402483;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402484;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402485;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402486;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402487;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402488;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402489;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402490;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402491;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402492;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402493;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402494;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402495;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402496;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402497;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402498;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402499;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402500;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402501;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402502;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402503;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402504;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402505;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402506;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402507;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402508;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402509;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402510;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402511;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402512;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402513;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402514;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402515;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402516;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402517;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402518;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402519;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402520;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402521;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402522;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402523;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402524;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402525;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402526;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402527;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402528;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402529;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402530;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402531;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402532;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402533;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402534;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402535;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402536;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402537;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402538;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402539;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402540;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402541;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402542;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402543;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402544;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402545;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402546;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402547;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402548;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402549;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402550;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402551;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402552;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402553;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402554;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402555;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402556;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402557;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402558;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402559;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402560;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402561;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402562;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402563;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402564;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402565;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402566;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402567;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402568;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402569;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402570;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402571;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402572;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402573;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402574;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402575;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402576;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402577;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402578;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402579;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402580;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402581;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402582;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402583;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402584;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402585;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402586;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402587;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402588;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402589;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402590;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402591;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402592;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402593;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402594;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402595;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402596;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402597;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402598;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402599;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402600;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402601;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402602;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402603;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402604;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402605;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402606;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402607;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402608;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402609;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402610;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402611;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402612;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402613;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402614;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402615;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402616;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402617;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402618;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402619;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402620;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402621;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402622;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402623;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402624;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402625;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402626;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402627;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402628;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402629;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402630;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402631;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402632;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402633;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402634;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402635;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402636;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402637;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402638;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402639;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402640;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402641;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402642;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402643;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402644;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402645;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402646;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402647;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402648;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402649;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402650;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402651;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402652;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402653;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402654;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402655;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402656;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402657;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402658;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402659;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402660;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402661;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402662;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402663;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402664;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402665;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402666;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402667;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402668;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402669;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402670;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402671;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402672;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402673;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402674;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402675;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402676;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402677;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402678;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402679;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402680;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402681;
UPDATE nrmn.survey SET protection_status='Military protected',inside_marine_park='No'WHERE survey_id=923402682;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402683;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402684;
UPDATE nrmn.survey SET protection_status='Fishing',inside_marine_park='No'WHERE survey_id=923402685;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402686;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402687;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402688;
UPDATE nrmn.survey SET protection_status='Military Protected',inside_marine_park='No'WHERE survey_id=923402689;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402690;
UPDATE nrmn.survey SET protection_status='No Take',inside_marine_park='Yes'WHERE survey_id=923402691;
END;