package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.AphiaRefEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
* Generated by Spring Data Generator on 10/01/2020
*/
@RepositoryRestResource
public interface AphiaRefEntityRepository extends JpaRepository<AphiaRefEntity, Integer>, JpaSpecificationExecutor<AphiaRefEntity> {

}
