package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.DiverRefEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 10/01/2020
*/
@Repository
public interface DiverRefEntityRepository extends JpaRepository<DiverRefEntity, Integer>, JpaSpecificationExecutor<DiverRefEntity> {
        public List<DiverRefEntity> findByInitials(String initials);
}
