package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.DiverRefEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.rest.core.annotation.Description;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 10/01/2020
*/

@RepositoryRestResource(collectionResourceDescription = @Description("Diver desc repo"),
itemResourceDescription = @Description("item diver desc"))
public interface DiverRefEntityRepository extends JpaRepository<DiverRefEntity, Integer>, JpaSpecificationExecutor<DiverRefEntity> {
         List<DiverRefEntity> findByInitials(String initials);
}
