package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.Diver;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 10/01/2020
*/
@Repository
public interface DiverRepository extends JpaRepository<Diver, Integer>, JpaSpecificationExecutor<Diver> {
        public List<Diver> findByInitials(String initials);
}
