package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.SecUserEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Repository;

import javax.swing.text.html.Option;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Stream;

/**
 * Generated by Spring Data Generator on 10/01/2020
 */
@Repository
public interface SecUserEntityRepository extends JpaRepository<SecUserEntity, Long>, JpaSpecificationExecutor<SecUserEntity> {
    Optional<SecUserEntity> findByEmail(String Email);

    ConcurrentHashMap<String, String> blackListedToken = new ConcurrentHashMap<String, String>();

    static Optional<String> addBlackListedToken(String email, String token) {
        return Optional.ofNullable(blackListedToken.putIfAbsent(email, token));
    }

    static  boolean blackListedTokenPresent(String email, String token) {
        return blackListedToken.getOrDefault(email, "").equals(token);
    }

}
