package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.SecUserEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
* Generated by Spring Data Generator on 10/01/2020
*/
@Repository
public interface SecUserEntityRepository extends JpaRepository<SecUserEntity, Long>, JpaSpecificationExecutor<SecUserEntity> {
    Optional<SecUserEntity> findByEmail(String Email);
}
