package au.org.aodn.nrmn.restapi.repository;

import au.org.aodn.nrmn.restapi.model.db.SecUserEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

/**
* Generated by Spring Data Generator on 10/01/2020
*/
@Repository
public interface UserSecEntityRepository extends JpaRepository<SecUserEntity, Integer>, JpaSpecificationExecutor<SecUserEntity> {

    @Query("SELECT distinct u FROM SecUserEntity u")
    Page<SecUserEntity> findAll(
            Pageable pageable,
            @Param("username") String username,
            @Param("searchNamePattern") String searchNamePattern//,
//            @Param("includeStatus") List<SecUserStatus> includeStatus
    );
}
