BEGIN;
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND61';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL17';
UPDATE nrmn.site_ref SET protection_status='Fishing' where site_code='BAL18';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='BAL11';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL12';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='BAL13';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL14';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='BAL15';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='BAL8';
UPDATE nrmn.site_ref SET protection_status='Fishing' where site_code='BAL20';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL21';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL22';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='BAL23';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='BAL10';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='BAL7';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='PVA14';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='PVA18';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAN102';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAN103';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAN98';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAN99';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN84';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN104';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN11';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN14';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN16';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN17';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN18';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN32';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN33';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN34';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN37';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN38';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN44';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN45';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN54';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN55';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN56';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN57';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN58';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN59';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN60';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN61';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN62';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN63';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN64';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN65';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN66';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN67';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN68';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN78';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAN86';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CANT4';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT27';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT28';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT29';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT30';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT31';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT32';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT33';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT34';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='CAT35';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='CAT39';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='GALI1';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='GALI18';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='GALI2';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='GALI3';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='GALI4';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='GALI5';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='GALI6';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='GALI7';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND13';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND16';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND18';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND19';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND20';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND22';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND23';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND24';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND25';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND26';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND27';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND28';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND29';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND30';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND35';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND36 ';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND37';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND21';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND38';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND39';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND46';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND47';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND48';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND52';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='AND53';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND55';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND56';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND57';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND58';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND60';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND63';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='AND64';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND65';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='AND66';
UPDATE nrmn.site_ref SET protection_status='Fishing' where site_code='MURC5';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='MURC6';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='MURC7';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='MURC3';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='MURC2';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='MURC4';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='VAL19';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='VAL20';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='VAL10';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='VAL11';
UPDATE nrmn.site_ref SET protection_status='Restricted take' where site_code='VAL12';
UPDATE nrmn.site_ref SET protection_status='Restricted take multizoned' where site_code='VAL15';
UPDATE nrmn.site_ref SET protection_status='No take' where site_code='VAL9';
END;
