BEGIN TRANSACTION;
ALTER TABLE nrmn.survey DROP IF EXISTS created;
ALTER TABLE nrmn.survey DROP IF EXISTS updated;
ALTER TABLE nrmn.survey_aud DROP IF EXISTS created;
ALTER TABLE nrmn.survey_aud DROP IF EXISTS created_mod;
ALTER TABLE nrmn.survey_aud DROP IF EXISTS updated;
ALTER TABLE nrmn.survey_aud DROP IF EXISTS updated_mod;
ALTER TABLE nrmn.survey ADD COLUMN created TIMESTAMP;
ALTER TABLE nrmn.survey ADD COLUMN updated TIMESTAMP;
ALTER TABLE nrmn.survey_aud ADD COLUMN updated TIMESTAMP;
ALTER TABLE nrmn.survey_aud ADD COLUMN updated_mod BOOLEAN;
ALTER TABLE nrmn.survey_aud ADD COLUMN created TIMESTAMP;
ALTER TABLE nrmn.survey_aud ADD COLUMN created_mod BOOLEAN;
END;
