UPDATE nrmn.pq_category_ref SET major_category_name='Changes (to new major_category)' where category_id=category_id;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=1;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=2;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=3;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=4;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=5;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=6;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=7;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=8;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=9;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=10;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=11;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=12;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=13;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=14;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=15;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=16;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=17;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=18;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=19;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=20;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=21;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=22;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=23;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=24;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=25;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=26;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals_Bleached' where category_id=27;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=28;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=29;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=30;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=31;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=32;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=33;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals_Bleached' where category_id=34;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=35;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=36;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=37;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=38;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=39;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=40;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=41;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=42;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=43;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=44;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=45;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=46;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=47;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=48;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=49;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=50;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=51;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=52;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=53;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=54;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=55;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals_Bleached' where category_id=56;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=57;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=58;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=59;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=60;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=61;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=62;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=63;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=64;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=65;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=66;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=67;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=68;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=69;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=70;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=71;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=72;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=73;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=74;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=75;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=76;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=77;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals_Bleached' where category_id=78;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=79;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=80;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=81;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=82;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=83;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=84;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=85;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=86;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=87;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=88;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=89;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=90;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=91;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=92;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=93;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=94;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=95;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=96;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=97;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals_Bleached' where category_id=98;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=99;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=100;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=101;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=102;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=103;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=104;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals_Bleached' where category_id=105;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=106;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=107;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=108;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=109;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=110;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=111;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=112;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=113;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=114;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=115;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=116;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=117;
UPDATE nrmn.pq_category_ref SET major_category_name='Ahermatypic corals' where category_id=118;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=119;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=120;
UPDATE nrmn.pq_category_ref SET major_category_name='Slime (not trapping sediment)' where category_id=121;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=122;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=123;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=124;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=125;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=126;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=127;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=128;
UPDATE nrmn.pq_category_ref SET major_category_name='Solitary Anemones' where category_id=129;
UPDATE nrmn.pq_category_ref SET major_category_name='Solitary Anemones' where category_id=130;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=131;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=132;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=133;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=134;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (stalked)' where category_id=135;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=136;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=137;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=138;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=139;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=140;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=141;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=142;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=143;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=144;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=145;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=146;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=147;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=148;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=149;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=150;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=151;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=152;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=153;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=154;
UPDATE nrmn.pq_category_ref SET major_category_name='Bare Rock' where category_id=155;
UPDATE nrmn.pq_category_ref SET major_category_name='Barnacles' where category_id=156;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=157;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=158;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=159;
UPDATE nrmn.pq_category_ref SET major_category_name='Black & Octocorals' where category_id=160;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals_Bleached' where category_id=161;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=162;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=163;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=164;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals_Bleached' where category_id=165;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=166;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=167;
UPDATE nrmn.pq_category_ref SET major_category_name='Bottlebrush Acropora corals' where category_id=168;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=169;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=170;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=171;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=172;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=173;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=174;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=175;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=176;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=177;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora_Bleached' where category_id=178;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=179;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=180;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous brown algae_epiphyte' where category_id=181;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=182;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=183;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=184;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=185;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoa' where category_id=186;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (hard)' where category_id=187;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (soft)' where category_id=188;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (soft)' where category_id=189;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=190;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=191;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=192;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=193;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=194;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=195;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=196;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=197;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=198;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=199;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=200;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=201;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=202;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=203;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=204;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=205;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=206;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=207;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=208;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=209;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=210;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=211;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=212;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=213;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=214;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=215;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=216;
UPDATE nrmn.pq_category_ref SET major_category_name='Caulerpa' where category_id=217;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=218;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=219;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=220;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=221;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=222;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=223;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=224;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=225;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=226;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=227;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=228;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=229;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=230;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=231;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=232;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=233;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=234;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=235;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=236;
UPDATE nrmn.pq_category_ref SET major_category_name='Cnidaria' where category_id=237;
UPDATE nrmn.pq_category_ref SET major_category_name='Cnidaria' where category_id=238;
UPDATE nrmn.pq_category_ref SET major_category_name='Cobble' where category_id=239;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=240;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=241;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=242;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=243;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=244;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=245;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=246;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=247;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=248;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=249;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=250;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=251;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs_Bleached' where category_id=252;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=253;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=254;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals_Bleached' where category_id=255;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals_Bleached' where category_id=256;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=257;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=258;
UPDATE nrmn.pq_category_ref SET major_category_name='Coral rubble' where category_id=259;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=260;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=261;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=262;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=263;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=264;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=265;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=266;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=267;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=268;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals_Bleached' where category_id=269;
UPDATE nrmn.pq_category_ref SET major_category_name='Corymbose Acropora corals' where category_id=270;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=271;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=272;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=273;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=274;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=275;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=276;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=277;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustacea' where category_id=278;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=279;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=280;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=281;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)_Bleached' where category_id=282;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=283;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=284;
UPDATE nrmn.pq_category_ref SET major_category_name='Ahermatypic corals' where category_id=285;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=286;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous brown algae_epiphyte' where category_id=287;
UPDATE nrmn.pq_category_ref SET major_category_name='Slime (not trapping sediment)' where category_id=288;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=289;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=290;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=291;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=292;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=293;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=294;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=295;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=296;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=297;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=298;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=299;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=300;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=301;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=302;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=303;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=304;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=305;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=306;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=307;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=308;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=309;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=310;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=311;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=312;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=313;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=314;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=315;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=316;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=317;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=318;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=319;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=320;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=321;
UPDATE nrmn.pq_category_ref SET major_category_name='Bare Rock' where category_id=322;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=323;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=324;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=325;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=326;
UPDATE nrmn.pq_category_ref SET major_category_name='Desmarestia and Himantothallus' where category_id=327;
UPDATE nrmn.pq_category_ref SET major_category_name='Desmarestia and Himantothallus' where category_id=328;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=329;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=330;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=331;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=332;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=333;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=334;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=335;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=336;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=337;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=338;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=339;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals' where category_id=340;
UPDATE nrmn.pq_category_ref SET major_category_name='Digitate corals_Bleached' where category_id=341;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=342;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=343;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=344;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=345;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=346;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=347;
UPDATE nrmn.pq_category_ref SET major_category_name='Durvillaea' where category_id=348;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=349;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=350;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=351;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=352;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=353;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=354;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=355;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=356;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=357;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=358;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=359;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=360;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=361;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=362;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=363;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=364;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=365;
UPDATE nrmn.pq_category_ref SET major_category_name='Ecklonia radiata' where category_id=366;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting leathery algae' where category_id=367;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (hard)' where category_id=368;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=369;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=370;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=371;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=372;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting leathery algae' where category_id=373;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting leathery algae' where category_id=374;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting leathery algae' where category_id=375;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=376;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=377;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=378;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=379;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=380;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=381;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=382;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=383;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=384;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=385;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=386;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=387;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=388;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=389;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=390;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=391;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=392;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=393;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=394;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=395;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=396;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=397;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=398;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=399;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=400;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=401;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=402;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=403;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=404;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=405;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=406;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=407;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=408;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=409;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=410;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=411;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=412;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=413;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=414;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=415;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=416;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=417;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=418;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous algae_epiphyte' where category_id=419;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=420;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=421;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous rock-attached algae' where category_id=422;
UPDATE nrmn.pq_category_ref SET major_category_name='Polychaete' where category_id=423;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=424;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals_Bleached' where category_id=425;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=426;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=427;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)_Bleached' where category_id=428;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=429;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=430;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=431;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=432;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=433;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=434;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=435;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=436;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=437;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=438;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=439;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=440;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=441;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=442;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=443;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=444;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=445;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=446;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=447;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=448;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=449;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=450;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=451;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=452;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=453;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=454;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=455;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=456;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=457;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=458;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals_Bleached' where category_id=459;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=460;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=461;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=462;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=463;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=464;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=465;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=466;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=467;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=468;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=469;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=470;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=471;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=472;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=473;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=474;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=475;
UPDATE nrmn.pq_category_ref SET major_category_name='Pebbles/gravel/shell' where category_id=476;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous green algae_epiphyte' where category_id=477;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=478;
UPDATE nrmn.pq_category_ref SET major_category_name='Green calcified algae (Halimeda)' where category_id=479;
UPDATE nrmn.pq_category_ref SET major_category_name='Green calcified algae (Halimeda)' where category_id=480;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=481;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=482;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=483;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=484;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=485;
UPDATE nrmn.pq_category_ref SET major_category_name='Green calcified algae (Halimeda)' where category_id=486;
UPDATE nrmn.pq_category_ref SET major_category_name='Green calcified algae (Halimeda)' where category_id=487;
UPDATE nrmn.pq_category_ref SET major_category_name='Green calcified algae (Halimeda)' where category_id=488;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=489;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=490;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=491;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (Halophila)' where category_id=492;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (Halophila)' where category_id=493;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=494;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=495;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=496;
UPDATE nrmn.pq_category_ref SET major_category_name='Heliopora coerulea (blue coral)' where category_id=497;
UPDATE nrmn.pq_category_ref SET major_category_name='Heliopora coerulea (blue coral)' where category_id=498;
UPDATE nrmn.pq_category_ref SET major_category_name='Heliopora coerulea (blue coral)_Bleached' where category_id=499;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=500;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=501;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=502;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=503;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=504;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=505;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=506;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous brown algae_epiphyte' where category_id=507;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=508;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=509;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=510;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=511;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=512;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=513;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=514;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=515;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=516;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral_Bleached' where category_id=517;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=518;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydroids' where category_id=519;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=520;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=521;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=522;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=523;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=524;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=525;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=526;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=527;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=528;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=529;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=530;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=531;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=532;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=533;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=534;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=535;
UPDATE nrmn.pq_category_ref SET major_category_name='Large brown laminarian kelps' where category_id=536;
UPDATE nrmn.pq_category_ref SET major_category_name='Large brown laminarian kelps' where category_id=537;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=538;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)_Bleached' where category_id=539;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=540;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=541;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)_Bleached' where category_id=542;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=543;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=544;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=545;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=546;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=547;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=548;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=549;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=550;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=551;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=552;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=553;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=554;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=555;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=556;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=557;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=558;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=559;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=560;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=561;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=562;
UPDATE nrmn.pq_category_ref SET major_category_name='Large brown laminarian kelps' where category_id=563;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=564;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=565;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=566;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=567;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=568;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=569;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=570;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=571;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=572;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=573;
UPDATE nrmn.pq_category_ref SET major_category_name='Macrocystis' where category_id=574;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydroids' where category_id=575;
UPDATE nrmn.pq_category_ref SET major_category_name='Forams' where category_id=576;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=577;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=578;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals_Bleached' where category_id=579;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=580;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=581;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=582;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=583;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=584;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals_Bleached' where category_id=585;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=586;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=587;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=588;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=589;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=590;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=591;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=592;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=593;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=594;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals_Bleached' where category_id=595;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=596;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=597;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=598;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=599;
UPDATE nrmn.pq_category_ref SET major_category_name='Molluscs' where category_id=600;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=601;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=602;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=603;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=604;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=605;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=606;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=607;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=608;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=609;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=610;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=611;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=612;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=613;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=614;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=615;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=616;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=617;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=618;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=619;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=620;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=621;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals_Bleached' where category_id=622;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=623;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals_Bleached' where category_id=624;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=625;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=626;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=627;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=628;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=629;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=630;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=631;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=632;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=633;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=634;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=635;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=636;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=637;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=638;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=639;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=640;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=641;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=642;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=643;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=644;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=645;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=646;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=647;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=648;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=649;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=650;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=651;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=652;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=653;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=654;
UPDATE nrmn.pq_category_ref SET major_category_name='Organ-pipe coral (Tubipora)' where category_id=655;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=656;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=657;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=658;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=659;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=660;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=661;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=662;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=663;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=664;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=665;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=666;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=667;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=668;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=669;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=670;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=671;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=672;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=673;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=674;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=675;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=676;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=677;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=678;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=679;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=680;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=681;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=682;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=683;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=684;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=685;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=686;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=687;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=688;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=689;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=690;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=691;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=692;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=693;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=694;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=695;
UPDATE nrmn.pq_category_ref SET major_category_name='Pebbles/gravel/shell' where category_id=696;
UPDATE nrmn.pq_category_ref SET major_category_name='Pebbles/gravel/shell' where category_id=697;
UPDATE nrmn.pq_category_ref SET major_category_name='Pebbles/gravel/shell' where category_id=698;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=699;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=700;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=701;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=702;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=703;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=704;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting leathery algae' where category_id=705;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=706;
UPDATE nrmn.pq_category_ref SET major_category_name='Phyllospora comosa' where category_id=707;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=708;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=709;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=710;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=711;
UPDATE nrmn.pq_category_ref SET major_category_name='Bare Rock' where category_id=712;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=713;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=714;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=715;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=716;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=717;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=718;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=719;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=720;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=721;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=722;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=723;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=724;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=725;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=726;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals_Bleached' where category_id=727;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=728;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=729;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=730;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=731;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=732;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=733;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=734;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora_Bleached' where category_id=735;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=736;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=737;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora_Bleached' where category_id=738;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=739;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=740;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=741;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=742;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=743;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora' where category_id=744;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Pocillopora_Bleached' where category_id=745;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=746;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=747;
UPDATE nrmn.pq_category_ref SET major_category_name='Polychaete' where category_id=748;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (hollow)' where category_id=874;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=749;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=750;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=751;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=752;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=753;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=754;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=755;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=756;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=757;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=758;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=759;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=760;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals_Bleached' where category_id=761;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=762;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=763;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=764;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=765;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=766;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=767;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=768;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=769;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=770;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=771;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=772;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals_Bleached' where category_id=773;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=774;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=775;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=776;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=777;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=778;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=779;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=780;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=781;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=782;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=783;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=784;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=785;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=786;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=787;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=788;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=789;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (stalked)' where category_id=790;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (stalked)' where category_id=791;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydroids' where category_id=792;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=793;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=794;
UPDATE nrmn.pq_category_ref SET major_category_name='Filamentous red algae_epiphyte' where category_id=795;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=796;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=797;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=798;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=799;
UPDATE nrmn.pq_category_ref SET major_category_name='Crustose coralline algae' where category_id=800;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=801;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=802;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=803;
UPDATE nrmn.pq_category_ref SET major_category_name='Bare Rock' where category_id=804;
UPDATE nrmn.pq_category_ref SET major_category_name='Bare Rock' where category_id=805;
UPDATE nrmn.pq_category_ref SET major_category_name='Coral rubble' where category_id=806;
UPDATE nrmn.pq_category_ref SET major_category_name='Polychaete' where category_id=807;
UPDATE nrmn.pq_category_ref SET major_category_name='Sand' where category_id=808;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=809;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=810;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)_Bleached' where category_id=811;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=812;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=813;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=814;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=815;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=816;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=817;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=818;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=819;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=820;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=821;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=822;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=823;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=824;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=825;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=826;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=827;
UPDATE nrmn.pq_category_ref SET major_category_name='Columnar corals' where category_id=828;
UPDATE nrmn.pq_category_ref SET major_category_name='Large-polyp stony corals (free-living)' where category_id=829;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=830;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=831;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=832;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrasses' where category_id=833;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (Halophila)' where category_id=834;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=835;
UPDATE nrmn.pq_category_ref SET major_category_name='Sand' where category_id=836;
UPDATE nrmn.pq_category_ref SET major_category_name='Sand' where category_id=837;
UPDATE nrmn.pq_category_ref SET major_category_name='Turfing algae (<2 cm high algal/sediment mat on rock)' where category_id=838;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=839;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=840;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=841;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=842;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=843;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=844;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=845;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=846;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=847;
UPDATE nrmn.pq_category_ref SET major_category_name='Polychaete' where category_id=848;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile bivalves' where category_id=849;
UPDATE nrmn.pq_category_ref SET major_category_name='Sessile gastropods' where category_id=850;
UPDATE nrmn.pq_category_ref SET major_category_name='Molluscs' where category_id=851;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=852;
UPDATE nrmn.pq_category_ref SET major_category_name='Sand' where category_id=853;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=854;
UPDATE nrmn.pq_category_ref SET major_category_name='Small <2cm foliose algal cover (not trapping sediment)' where category_id=855;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=856;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=857;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians_Bleached' where category_id=858;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=859;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (soft)' where category_id=860;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=861;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals_Bleached' where category_id=862;
UPDATE nrmn.pq_category_ref SET major_category_name='Solitary Anemones' where category_id=863;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=864;
UPDATE nrmn.pq_category_ref SET major_category_name='Polychaete' where category_id=865;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (encrusting)' where category_id=866;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (erect)' where category_id=867;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (erect)' where category_id=868;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (encrusting)' where category_id=869;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (erect)' where category_id=870;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (hollow)' where category_id=871;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (massive)' where category_id=872;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (encrusting)' where category_id=873;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (massive)' where category_id=875;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (encrusting)' where category_id=876;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=877;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora_Bleached' where category_id=878;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=879;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=880;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching Acropora' where category_id=881;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=882;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (erect)' where category_id=883;
UPDATE nrmn.pq_category_ref SET major_category_name='Hydrocoral' where category_id=884;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=885;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=886;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=887;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals' where category_id=888;
UPDATE nrmn.pq_category_ref SET major_category_name='Branching corals_Bleached' where category_id=889;
UPDATE nrmn.pq_category_ref SET major_category_name='Stony corals' where category_id=890;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=891;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals_Bleached' where category_id=892;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=893;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=894;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=895;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=896;
UPDATE nrmn.pq_category_ref SET major_category_name='Ascidians (unstalked)' where category_id=897;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=898;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=899;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=900;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=901;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=902;
UPDATE nrmn.pq_category_ref SET major_category_name='Sub-massive corals' where category_id=903;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=904;
UPDATE nrmn.pq_category_ref SET major_category_name='Geniculate coralline algae' where category_id=905;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals_Bleached' where category_id=906;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=907;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=908;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals_Bleached' where category_id=909;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=910;
UPDATE nrmn.pq_category_ref SET major_category_name='Tabular Acropora corals' where category_id=911;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=912;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=913;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=914;
UPDATE nrmn.pq_category_ref SET major_category_name='Sponges (massive)' where category_id=915;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose red algae' where category_id=916;
UPDATE nrmn.pq_category_ref SET major_category_name='Bryozoan (hard)' where category_id=917;
UPDATE nrmn.pq_category_ref SET major_category_name='Ahermatypic corals' where category_id=918;
UPDATE nrmn.pq_category_ref SET major_category_name='Ahermatypic corals' where category_id=919;
UPDATE nrmn.pq_category_ref SET major_category_name='Organ-pipe coral (Tubipora)' where category_id=920;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=921;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=922;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=923;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=924;
UPDATE nrmn.pq_category_ref SET major_category_name='Encrusting corals' where category_id=925;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=926;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=927;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=928;
UPDATE nrmn.pq_category_ref SET major_category_name='Foliose/Plate corals' where category_id=929;
UPDATE nrmn.pq_category_ref SET major_category_name='Dead coral' where category_id=930;
UPDATE nrmn.pq_category_ref SET major_category_name='Massive corals' where category_id=931;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=932;
UPDATE nrmn.pq_category_ref SET major_category_name='Large brown laminarian kelps' where category_id=933;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=934;
UPDATE nrmn.pq_category_ref SET major_category_name='Unscorable' where category_id=935;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose green algae' where category_id=936;
UPDATE nrmn.pq_category_ref SET major_category_name='Worms' where category_id=937;
UPDATE nrmn.pq_category_ref SET major_category_name='Soft corals and gorgonians' where category_id=938;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=939;
UPDATE nrmn.pq_category_ref SET major_category_name='Other fucoids' where category_id=940;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=941;
UPDATE nrmn.pq_category_ref SET major_category_name='Colonial Anemones, Zoanthids and Corallimorphs' where category_id=942;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=943;
UPDATE nrmn.pq_category_ref SET major_category_name='Medium foliose brown algae' where category_id=944;
UPDATE nrmn.pq_category_ref SET major_category_name='Seagrass (straplike)' where category_id=945;
