# This workflow versions, builds and archives the application when a release tag is created

name: Build Release Artifact

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn --frozen-lock-file --cwd web install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-southeast-2
          role-skip-session-tagging: true
          role-duration-seconds: 900
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Version
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - name: Build
        run: mvn --batch-mode clean package -Dmaven.test.skip=true
      - name: Generate Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/nrmn-version-repo/nrmn-version-repo/app/target/nrmn-app-*.war
      - name: Upload Artifact to S3
        run: |
          aws s3 cp \
          /home/runner/work/nrmn-version-repo/nrmn-version-repo/app/target/nrmn-app-*.war \
          s3://${{ secrets.AWS_ARTIFACT_BUCKET }}/promoted/python-aodncore/rc/
    timeout-minutes: 45
